# .github/workflows/schedule.yml

name: Scheduled TeamUp Scripts

on:
  push:
    branches: [ main ]
  schedule:
    # daily at 07:00 Doha (04:00 UTC)
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    env:
      TEAMUP_BASE_URL:    ${{ secrets.TEAMUP_BASE_URL }}
      TEAMUP_CALENDAR_KEY:${{ secrets.TEAMUP_CALENDAR_KEY }}
      TEAMUP_TOKEN:       ${{ secrets.TEAMUP_TOKEN }}
      TEAMUP_EMAIL:       ${{ secrets.TEAMUP_EMAIL }}
      TEAMUP_PASSWORD:    ${{ secrets.TEAMUP_PASSWORD }}
      SB_USERNAME:        ${{ secrets.SB_USERNAME }}
      SB_PASSWORD:        ${{ secrets.SB_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Delete all sub-calendars
        run: python delete_all_sub_calendars.py

      - name: Create sub-calendar structure
        run: python create_sub_calendar_structure.py

      - name: Push latest SB data to TeamUp
        run: python push_latest_sb_data_to_teamup.py
