# File: .github/workflows/schedule.yml

name: Scheduled TeamUp Scripts

# When to run:
on:
  push:
    branches:
      - main
  schedule:
    # daily at 07:00 Doha time
    - cron: '0 4 * * *'

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code
      - uses: actions/checkout@v3

      # 2) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Install your requirements
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4) Run your three scripts in sequence
      - name: Run all scripts
        run: |
          delete_all_sub_calendars.py
          create_sub_calendar_structure.py
          push_latest_sb_data_to_teamup.py

